/* Agent ROI dataset — verbatim from the flowx.ai/business-agents-roi-calculator
   embed. Compact keys keep the payload small:
     i = industry, s = stack / use case, n = agent name,
     d = department, t = minutes saved per process, v = (unused legacy value). */
export const ROI_DATA = [
  {"i":"Banking","s":"Commercial Onboarding","n":"Company Identity Extractor","d":"Onboarding / Lending","t":5,"v":2.6},
  {"i":"Banking","s":"Commercial Onboarding","n":"Shareholder & Beneficial Ownership Validator","d":"Onboarding / Compliance","t":10,"v":5.21},
  {"i":"Banking","s":"Commercial Onboarding","n":"Authorized Signatory & Empowerment Validator","d":"Onboarding / Legal","t":8,"v":4.17},
  {"i":"Banking","s":"Commercial Onboarding","n":"Address & Location Verifier","d":"Onboarding / Operations","t":3,"v":1.56},
  {"i":"Banking","s":"Commercial Onboarding","n":"Related-Party & Group Structure Mapper","d":"Onboarding / Risk","t":12,"v":6.25},
  {"i":"Banking","s":"Commercial Onboarding","n":"Document Completeness & Validity Checker","d":"Onboarding / Operations","t":4,"v":2.08},
  {"i":"Banking","s":"Commercial Onboarding","n":"Multi-Language Document Translator & Summarizer","d":"Onboarding / Operations","t":15,"v":7.81},

  {"i":"Banking","s":"Corporate Account Opening","n":"Entity Classification & Segmentation Agent","d":"Onboarding / Commercial","t":6,"v":3.13},
  {"i":"Banking","s":"Corporate Account Opening","n":"Account Type Recommender","d":"Onboarding / Product","t":7,"v":3.65},
  {"i":"Banking","s":"Corporate Account Opening","n":"Service & Product Bundling Agent","d":"Onboarding / Sales","t":10,"v":5.21},
  {"i":"Banking","s":"Corporate Account Opening","n":"Pricing & Fee Quoter","d":"Onboarding / Finance","t":8,"v":4.17},
  {"i":"Banking","s":"Corporate Account Opening","n":"Workflow Orchestration & Status Tracker","d":"Onboarding / Operations","t":5,"v":2.6},
  {"i":"Banking","s":"Corporate Account Opening","n":"Cross-Sell & Up-Sell Opportunity Finder","d":"Onboarding / Sales","t":9,"v":4.69},

  {"i":"Banking","s":"Retail Mortgage Underwriting","n":"Income & Employment Verifier","d":"Underwriting / Credit","t":12,"v":6.25},
  {"i":"Banking","s":"Retail Mortgage Underwriting","n":"Asset & Liability Analyzer","d":"Underwriting / Credit","t":10,"v":5.21},
  {"i":"Banking","s":"Retail Mortgage Underwriting","n":"Credit History & Score Assessor","d":"Underwriting / Credit","t":8,"v":4.17},
  {"i":"Banking","s":"Retail Mortgage Underwriting","n":"Property Valuation & Appraisal Validator","d":"Underwriting / Credit","t":15,"v":7.81},
  {"i":"Banking","s":"Retail Mortgage Underwriting","n":"Debt-to-Income & Affordability Calculator","d":"Underwriting / Credit","t":7,"v":3.65},
  {"i":"Banking","s":"Retail Mortgage Underwriting","n":"Compliance & Regulatory Checker","d":"Underwriting / Compliance","t":10,"v":5.21},
  {"i":"Banking","s":"Retail Mortgage Underwriting","n":"Fraud & Risk Flag Detector","d":"Underwriting / Risk","t":12,"v":6.25},
  {"i":"Banking","s":"Retail Mortgage Underwriting","n":"Loan Product Matcher & Recommender","d":"Underwriting / Product","t":8,"v":4.17},
  {"i":"Banking","s":"Retail Mortgage Underwriting","n":"Final Decision Synthesizer & Explainer","d":"Underwriting / Credit","t":10,"v":5.21},

  {"i":"Banking","s":"Commercial Lending","n":"Financial Statement Analyzer","d":"Lending / Credit","t":20,"v":10.42},
  {"i":"Banking","s":"Commercial Lending","n":"Cash Flow & Liquidity Projector","d":"Lending / Credit","t":18,"v":9.38},
  {"i":"Banking","s":"Commercial Lending","n":"Collateral Valuation & Sufficiency Agent","d":"Lending / Credit","t":15,"v":7.81},
  {"i":"Banking","s":"Commercial Lending","n":"Industry & Market Risk Assessor","d":"Lending / Risk","t":12,"v":6.25},
  {"i":"Banking","s":"Commercial Lending","n":"Covenant Design & Monitoring Agent","d":"Lending / Credit","t":10,"v":5.21},
  {"i":"Banking","s":"Commercial Lending","n":"Loan Structuring & Pricing Agent","d":"Lending / Product","t":14,"v":7.29},
  {"i":"Banking","s":"Commercial Lending","n":"Credit Committee Memo Drafter","d":"Lending / Credit","t":25,"v":13.02},

  {"i":"Banking","s":"SME/Corporate UW - financial insights","n":"P&L & Balance Sheet Extractor","d":"Underwriting / Credit","t":15,"v":7.81},
  {"i":"Banking","s":"SME/Corporate UW - financial insights","n":"Ratio & Trend Calculator","d":"Underwriting / Credit","t":12,"v":6.25},
  {"i":"Banking","s":"SME/Corporate UW - financial insights","n":"Working Capital & Burn Rate Analyzer","d":"Underwriting / Credit","t":10,"v":5.21},
  {"i":"Banking","s":"SME/Corporate UW - financial insights","n":"Revenue & Margin Forecaster","d":"Underwriting / Credit","t":20,"v":10.42},
  {"i":"Banking","s":"SME/Corporate UW - financial insights","n":"Sector Benchmark Comparator","d":"Underwriting / Risk","t":14,"v":7.29},
  {"i":"Banking","s":"SME/Corporate UW - financial insights","n":"Red Flag & Anomaly Detector","d":"Underwriting / Risk","t":8,"v":4.17},
  {"i":"Banking","s":"SME/Corporate UW - financial insights","n":"Management Quality & Governance Scorer","d":"Underwriting / Risk","t":12,"v":6.25},
  {"i":"Banking","s":"SME/Corporate UW - financial insights","n":"Credit Rating Estimator","d":"Underwriting / Credit","t":10,"v":5.21},

  {"i":"Banking","s":"Trade Finance Invoice Factoring","n":"Invoice Authenticity Validator","d":"Trade Finance / Operations","t":8,"v":4.17},
  {"i":"Banking","s":"Trade Finance Invoice Factoring","n":"Debtor Creditworthiness Checker","d":"Trade Finance / Credit","t":12,"v":6.25},
  {"i":"Banking","s":"Trade Finance Invoice Factoring","n":"Advance Rate & Pricing Calculator","d":"Trade Finance / Product","t":10,"v":5.21},
  {"i":"Banking","s":"Trade Finance Invoice Factoring","n":"Duplicate & Fraud Detector","d":"Trade Finance / Risk","t":15,"v":7.81},
  {"i":"Banking","s":"Trade Finance Invoice Factoring","n":"Collection Probability Estimator","d":"Trade Finance / Credit","t":12,"v":6.25},
  {"i":"Banking","s":"Trade Finance Invoice Factoring","n":"Portfolio Concentration Monitor","d":"Trade Finance / Risk","t":10,"v":5.21},

  {"i":"Banking","s":"Garnishment Processing","n":"Court Order Document Parser","d":"Operations / Legal","t":10,"v":5.21},
  {"i":"Banking","s":"Garnishment Processing","n":"Priority & Precedence Determiner","d":"Operations / Legal","t":8,"v":4.17},
  {"i":"Banking","s":"Garnishment Processing","n":"Calculation & Withholding Agent","d":"Operations / Payroll","t":12,"v":6.25},
  {"i":"Banking","s":"Garnishment Processing","n":"Customer Account Freeze & Hold Manager","d":"Operations / Compliance","t":7,"v":3.65},
  {"i":"Banking","s":"Garnishment Processing","n":"Payment Remittance & Reporting Agent","d":"Operations / Finance","t":10,"v":5.21},
  {"i":"Banking","s":"Garnishment Processing","n":"Multi-Garnishment Prioritizer","d":"Operations / Legal","t":15,"v":7.81},

  {"i":"Banking","s":"Financial Crime Risk Assessment","n":"Transaction Pattern Analyzer","d":"Compliance / AML","t":20,"v":10.42},
  {"i":"Banking","s":"Financial Crime Risk Assessment","n":"Sanctions & PEP Screener","d":"Compliance / AML","t":15,"v":7.81},
  {"i":"Banking","s":"Financial Crime Risk Assessment","n":"Risk Score Aggregator & Tiering Agent","d":"Compliance / Risk","t":12,"v":6.25},
  {"i":"Banking","s":"Financial Crime Risk Assessment","n":"SAR/STR Draft Generator","d":"Compliance / AML","t":25,"v":13.02},
  {"i":"Banking","s":"Financial Crime Risk Assessment","n":"Network & Link Analysis Agent","d":"Compliance / AML","t":18,"v":9.38},

  {"i":"Banking","s":"Customer Churn & Retention","n":"Usage & Engagement Tracker","d":"Marketing / CRM","t":10,"v":5.21},
  {"i":"Banking","s":"Customer Churn & Retention","n":"Churn Probability Predictor","d":"Marketing / Analytics","t":15,"v":7.81},
  {"i":"Banking","s":"Customer Churn & Retention","n":"Personalized Retention Offer Generator","d":"Marketing / Product","t":12,"v":6.25},
  {"i":"Banking","s":"Customer Churn & Retention","n":"Win-Back Campaign Agent","d":"Marketing / CRM","t":10,"v":5.21},

  {"i":"Banking","s":"AML KYC","n":"Customer Due Diligence (CDD) Orchestrator","d":"Compliance / AML","t":20,"v":10.42},
  {"i":"Banking","s":"AML KYC","n":"Enhanced Due Diligence (EDD) Trigger & Executor","d":"Compliance / AML","t":25,"v":13.02},
  {"i":"Banking","s":"AML KYC","n":"Ongoing Monitoring & Refresh Agent","d":"Compliance / AML","t":15,"v":7.81},
  {"i":"Banking","s":"AML KYC","n":"Adverse Media & News Scanner","d":"Compliance / AML","t":18,"v":9.38},

  {"i":"Banking","s":"Stand-alone Quick Win","n":"Document Digitization & OCR Agent","d":"Operations / IT","t":5,"v":2.6},
  {"i":"Banking","s":"Stand-alone Quick Win","n":"Email & Query Auto-Responder","d":"Operations / Customer Service","t":3,"v":1.56},
  {"i":"Banking","s":"Stand-alone Quick Win","n":"Meeting Summarizer & Action Tracker","d":"Operations / Admin","t":8,"v":4.17},
  {"i":"Banking","s":"Stand-alone Quick Win","n":"Contract Clause Extractor","d":"Operations / Legal","t":12,"v":6.25},
  {"i":"Banking","s":"Stand-alone Quick Win","n":"Expense Report Validator","d":"Operations / Finance","t":6,"v":3.13},
  {"i":"Banking","s":"Stand-alone Quick Win","n":"Customer Feedback Sentiment Analyzer","d":"Operations / CX","t":7,"v":3.65},
  {"i":"Banking","s":"Stand-alone Quick Win","n":"Regulatory Change Monitor & Summarizer","d":"Compliance / Risk","t":15,"v":7.81},

  {"i":"Insurance","s":"Policy Onboarding","n":"Application Form Digitizer & Parser","d":"Underwriting / Operations","t":8,"v":4.17},
  {"i":"Insurance","s":"Policy Onboarding","n":"Medical Record & History Extractor","d":"Underwriting / Medical","t":20,"v":10.42},
  {"i":"Insurance","s":"Policy Onboarding","n":"Risk Classification & Pricing Agent","d":"Underwriting / Actuarial","t":15,"v":7.81},
  {"i":"Insurance","s":"Policy Onboarding","n":"Underwriting Decision Support Agent","d":"Underwriting / Operations","t":18,"v":9.38},
  {"i":"Insurance","s":"Policy Onboarding","n":"Policy Document Generator","d":"Underwriting / Operations","t":10,"v":5.21},
  {"i":"Insurance","s":"Policy Onboarding","n":"Compliance & Regulatory Check Agent","d":"Underwriting / Compliance","t":12,"v":6.25},

  {"i":"Insurance","s":"Claims Processing","n":"First Notice of Loss (FNOL) Intake Agent","d":"Claims / Operations","t":10,"v":5.21},
  {"i":"Insurance","s":"Claims Processing","n":"Document & Evidence Collector","d":"Claims / Operations","t":12,"v":6.25},
  {"i":"Insurance","s":"Claims Processing","n":"Claim Validity & Coverage Checker","d":"Claims / Adjusting","t":15,"v":7.81},
  {"i":"Insurance","s":"Claims Processing","n":"Damage Assessment & Estimation Agent","d":"Claims / Adjusting","t":20,"v":10.42},
  {"i":"Insurance","s":"Claims Processing","n":"Settlement Calculator & Approver","d":"Claims / Finance","t":18,"v":9.38},
  {"i":"Insurance","s":"Claims Processing","n":"Payment Processing & Disbursement Agent","d":"Claims / Finance","t":8,"v":4.17},

  {"i":"Insurance","s":"Underwriting Assessment","n":"Submission Triage & Routing Agent","d":"Underwriting / Operations","t":7,"v":3.65},
  {"i":"Insurance","s":"Underwriting Assessment","n":"Risk Data Enrichment Agent","d":"Underwriting / Analytics","t":12,"v":6.25},
  {"i":"Insurance","s":"Underwriting Assessment","n":"Loss History & Claims Analyzer","d":"Underwriting / Actuarial","t":15,"v":7.81},
  {"i":"Insurance","s":"Underwriting Assessment","n":"Underwriting Guidelines Interpreter","d":"Underwriting / Operations","t":10,"v":5.21},
  {"i":"Insurance","s":"Underwriting Assessment","n":"Quote Generation & Comparison Agent","d":"Underwriting / Product","t":14,"v":7.29},
  {"i":"Insurance","s":"Underwriting Assessment","n":"Referral & Exception Handler","d":"Underwriting / Operations","t":12,"v":6.25},

  {"i":"Insurance","s":"Fraud Detection & Alerting","n":"Claim Pattern Anomaly Detector","d":"Claims / SIU","t":18,"v":9.38},
  {"i":"Insurance","s":"Fraud Detection & Alerting","n":"Historical Fraud Indicator Matcher","d":"Claims / SIU","t":15,"v":7.81},
  {"i":"Insurance","s":"Fraud Detection & Alerting","n":"Network & Link Analysis Agent","d":"Claims / SIU","t":20,"v":10.42},
  {"i":"Insurance","s":"Fraud Detection & Alerting","n":"Investigation Case Prioritizer","d":"Claims / SIU","t":10,"v":5.21},
  {"i":"Insurance","s":"Fraud Detection & Alerting","n":"Fraud Score & Alert Generator","d":"Claims / SIU","t":12,"v":6.25},

  {"i":"Insurance","s":"Renewals & Upsell","n":"Renewal Eligibility & Pricing Agent","d":"Policy Admin / Retention","t":12,"v":6.25},
  {"i":"Insurance","s":"Renewals & Upsell","n":"Customer Retention Risk Predictor","d":"Policy Admin / Analytics","t":15,"v":7.81},
  {"i":"Insurance","s":"Renewals & Upsell","n":"Cross-Sell & Up-Sell Recommender","d":"Policy Admin / Sales","t":10,"v":5.21},
  {"i":"Insurance","s":"Renewals & Upsell","n":"Personalized Renewal Offer Generator","d":"Policy Admin / Marketing","t":14,"v":7.29},
  {"i":"Insurance","s":"Renewals & Upsell","n":"Lapse & Non-Renewal Preventer","d":"Policy Admin / Retention","t":12,"v":6.25},

  {"i":"Insurance","s":"Insurance Regulatory & Compliance","n":"Policy Language & Compliance Checker","d":"Compliance / Legal","t":15,"v":7.81},
  {"i":"Insurance","s":"Insurance Regulatory & Compliance","n":"Rate Filing & Approval Tracker","d":"Compliance / Actuarial","t":12,"v":6.25},
  {"i":"Insurance","s":"Insurance Regulatory & Compliance","n":"Licensing & Authority Validator","d":"Compliance / Operations","t":8,"v":4.17},
  {"i":"Insurance","s":"Insurance Regulatory & Compliance","n":"Regulatory Reporting Agent","d":"Compliance / Finance","t":20,"v":10.42},
  {"i":"Insurance","s":"Insurance Regulatory & Compliance","n":"Audit Trail & Documentation Agent","d":"Compliance / Operations","t":10,"v":5.21},

  {"i":"Insurance","s":"Insurance Distribution","n":"Agent/Broker Onboarding & Credentialing","d":"Distribution / Operations","t":15,"v":7.81},
  {"i":"Insurance","s":"Insurance Distribution","n":"Commission Calculation & Reconciliation Agent","d":"Distribution / Finance","t":18,"v":9.38},
  {"i":"Insurance","s":"Insurance Distribution","n":"Performance Tracking & Incentive Agent","d":"Distribution / Sales","t":12,"v":6.25},
  {"i":"Insurance","s":"Insurance Distribution","n":"Lead Distribution & Assignment Agent","d":"Distribution / Sales","t":8,"v":4.17},
  {"i":"Insurance","s":"Insurance Distribution","n":"Training & Compliance Monitor","d":"Distribution / HR","t":10,"v":5.21},

  {"i":"Insurance","s":"Reinsurance Coordination","n":"Reinsurance Treaty Analyzer","d":"Reinsurance / Actuarial","t":20,"v":10.42},
  {"i":"Insurance","s":"Reinsurance Coordination","n":"Cession Calculation & Allocation Agent","d":"Reinsurance / Finance","t":15,"v":7.81},
  {"i":"Insurance","s":"Reinsurance Coordination","n":"Bordereau & Reporting Agent","d":"Reinsurance / Operations","t":18,"v":9.38},
  {"i":"Insurance","s":"Reinsurance Coordination","n":"Claims Recovery & Reimbursement Tracker","d":"Reinsurance / Claims","t":12,"v":6.25},
  {"i":"Insurance","s":"Reinsurance Coordination","n":"Reinsurer Relationship & Performance Monitor","d":"Reinsurance / Strategy","t":10,"v":5.21},

  {"i":"Insurance","s":"Complaint & Dispute","n":"Complaint Intake & Categorizer","d":"Customer Service / Operations","t":8,"v":4.17},
  {"i":"Insurance","s":"Complaint & Dispute","n":"Root Cause & Sentiment Analyzer","d":"Customer Service / Analytics","t":12,"v":6.25},
  {"i":"Insurance","s":"Complaint & Dispute","n":"Resolution Recommendation Agent","d":"Customer Service / Operations","t":15,"v":7.81},
  {"i":"Insurance","s":"Complaint & Dispute","n":"Regulatory Complaint Reporter","d":"Customer Service / Compliance","t":10,"v":5.21},

  {"i":"Logistics – Carriers","s":"Fleet Optimization","n":"Load Matching Agent","d":"Operations / Dispatch","t":15,"v":8.13},
  {"i":"Logistics – Carriers","s":"Fleet Optimization","n":"Utilization Insights Agent","d":"Operations / Analytics","t":15,"v":8.75},
  {"i":"Logistics – Carriers","s":"Predictive Maintenance","n":"Service History Analyzer Agent","d":"Maintenance / Reliability","t":15,"v":7.50},
  {"i":"Logistics – Carriers","s":"Predictive Maintenance","n":"Failure Prediction Agent","d":"Maintenance / Reliability","t":15,"v":9.38},
  {"i":"Logistics – Carriers","s":"Predictive Maintenance","n":"Maintenance Planner Agent","d":"Maintenance / Planning","t":15,"v":8.13},
  {"i":"Logistics – Carriers","s":"Predictive Maintenance","n":"Cost Optimization Agent","d":"Maintenance / Procurement","t":15,"v":8.75},
  {"i":"Logistics – Carriers","s":"Load Entry","n":"Load Intake Agent","d":"Back Office / Intake","t":5,"v":2.08},
  {"i":"Logistics – Carriers","s":"Load Entry","n":"Document Intelligence Agent","d":"Back Office / Ops","t":5,"v":2.29},
  {"i":"Logistics – Carriers","s":"Load Entry","n":"Data Validation Agent","d":"Back Office / Quality","t":10,"v":4.58},
  {"i":"Logistics – Carriers","s":"Load Entry","n":"Data Enrichment Agent","d":"Back Office / Ops","t":5,"v":2.29},
  {"i":"Logistics – Carriers","s":"Load Entry","n":"System Sync Agent","d":"Back Office / IT","t":15,"v":7.50},
  {"i":"Logistics – Carriers","s":"Fuel Efficiency","n":"Efficiency Insights Agent","d":"Operations / Analytics","t":15,"v":8.75},
  {"i":"Logistics – Carriers","s":"Fuel Efficiency","n":"Driver Performance Agent","d":"Safety / Ops","t":15,"v":8.13},
  {"i":"Logistics – Carriers","s":"Fuel Efficiency","n":"Sustainability Analytics Agent","d":"Sustainability / Reporting","t":15,"v":9.38},
  {"i":"Logistics – Carriers","s":"Compliance & Safety","n":"Regulatory Monitor Agent","d":"Compliance / Safety","t":15,"v":8.13},
  {"i":"Logistics – Carriers","s":"Compliance & Safety","n":"Driver Log Validator Agent","d":"Compliance / Safety","t":10,"v":4.58},
  {"i":"Logistics – Carriers","s":"Compliance & Safety","n":"Inspection Prep Agent","d":"Compliance / Safety","t":15,"v":7.50},
  {"i":"Logistics – Carriers","s":"Compliance & Safety","n":"Incident Reporting Agent","d":"Compliance / Safety","t":30,"v":13.75},
  {"i":"Logistics – Carriers","s":"Compliance & Safety","n":"Corrective Action Planner Agent","d":"Compliance / Safety","t":15,"v":8.75},
  {"i":"Logistics – Carriers","s":"Compliance & Safety","n":"Safety Score Optimizer Agent","d":"Compliance / Safety","t":15,"v":9.38},
  {"i":"Logistics – Carriers","s":"Customer Service","n":"Shipment Status Assistant Agent","d":"Customer Service","t":5,"v":2.29},
  {"i":"Logistics – Carriers","s":"Customer Service","n":"Exception Communication Agent","d":"Customer Service","t":10,"v":4.58},
  {"i":"Logistics – Carriers","s":"Customer Service","n":"Proactive Delay Notification Agent","d":"Customer Service","t":10,"v":4.58},
  {"i":"Logistics – Carriers","s":"Customer Service","n":"Customer SLA Risk Monitor Agent","d":"Customer Service / Operations","t":10,"v":5.00},

  {"i":"Logistics – 3PLs","s":"Inventory Optimization","n":"Demand Signal Analyzer Agent","d":"Inventory / Analytics","t":15,"v":8.13},
  {"i":"Logistics – 3PLs","s":"Inventory Optimization","n":"Reorder & Safety Stock Recommender Agent","d":"Inventory / Planning","t":15,"v":8.75},
  {"i":"Logistics – 3PLs","s":"Inventory Optimization","n":"Slow/Dead Stock Identifier Agent","d":"Inventory / Analytics","t":15,"v":9.38},
  {"i":"Logistics – 3PLs","s":"Exception Management","n":"Exception Classification Agent","d":"Operations / Customer Service","t":10,"v":4.58},
  {"i":"Logistics – 3PLs","s":"Exception Management","n":"Root Cause Analysis Agent","d":"Operations / Analytics","t":15,"v":8.13},
  {"i":"Logistics – 3PLs","s":"Exception Management","n":"Resolution Playbook Agent","d":"Operations / Customer Service","t":15,"v":8.75},
  {"i":"Logistics – 3PLs","s":"Labor Planning","n":"Volume & Labor Forecasting Agent","d":"Operations / Planning","t":15,"v":8.13},
  {"i":"Logistics – 3PLs","s":"Labor Planning","n":"Shift & Staffing Recommender Agent","d":"Operations / Planning","t":15,"v":8.75},
  {"i":"Logistics – 3PLs","s":"Labor Planning","n":"Overtime & Cost Control Agent","d":"Operations / Finance","t":15,"v":8.75},
  {"i":"Logistics – 3PLs","s":"Warehouse Operations","n":"Task Prioritization Agent","d":"Operations / Warehouse","t":10,"v":4.58},
  {"i":"Logistics – 3PLs","s":"Warehouse Operations","n":"Slotting & Layout Suggestion Agent","d":"Operations / Warehouse","t":15,"v":8.13},
  {"i":"Logistics – 3PLs","s":"Warehouse Operations","n":"Pick Path Optimization Agent","d":"Operations / Warehouse","t":15,"v":8.75},
  {"i":"Logistics – 3PLs","s":"Warehouse Operations","n":"Exception Triage Agent","d":"Operations / Warehouse","t":10,"v":4.58},
  {"i":"Logistics – 3PLs","s":"Billing & Revenue","n":"Billing Accuracy Validator Agent","d":"Finance / Billing","t":10,"v":4.58},
  {"i":"Logistics – 3PLs","s":"Billing & Revenue","n":"Revenue Leakage Detector Agent","d":"Finance / Revenue Assurance","t":15,"v":8.75},
  {"i":"Logistics – 3PLs","s":"Billing & Revenue","n":"Contract Compliance Agent","d":"Finance / Audit","t":15,"v":8.75},
  {"i":"Logistics – 3PLs","s":"Customer Reporting","n":"KPI & SLA Reporting Agent","d":"Customer Service / Reporting","t":15,"v":8.13},
  {"i":"Logistics – 3PLs","s":"Customer Reporting","n":"Root Cause Narrative Agent","d":"Customer Service / Reporting","t":15,"v":8.75},
  {"i":"Logistics – 3PLs","s":"Customer Reporting","n":"Continuous Improvement Suggestion Agent","d":"Customer Service / CI","t":15,"v":9.38},
  {"i":"Logistics – 3PLs","s":"Onboarding","n":"Customer Requirements Intake Agent","d":"Implementation / Onboarding","t":15,"v":8.13},
  {"i":"Logistics – 3PLs","s":"Onboarding","n":"Process Mapping Agent","d":"Implementation / Onboarding","t":15,"v":8.75},
  {"i":"Logistics – 3PLs","s":"Onboarding","n":"SOP Drafting Agent","d":"Implementation / Onboarding","t":15,"v":9.38},

  {"i":"Logistics – Brokers","s":"Carrier Matching","n":"Best-Fit Carrier Selector Agent","d":"Operations / Carrier Management","t":15,"v":8.13},
  {"i":"Logistics – Brokers","s":"Carrier Matching","n":"Carrier Performance Insight Agent","d":"Carrier Management / Analytics","t":15,"v":8.75},
  {"i":"Logistics – Brokers","s":"Carrier Matching","n":"Cost & Service Trade-off Agent","d":"Carrier Management / Pricing","t":15,"v":9.38},
  {"i":"Logistics – Brokers","s":"Inbox Management","n":"Email Intake & Parsing Agent","d":"Operations / Sales Support","t":5,"v":2.29},
  {"i":"Logistics – Brokers","s":"Inbox Management","n":"Lead Prioritization Agent","d":"Sales / Operations","t":10,"v":4.58},
  {"i":"Logistics – Brokers","s":"Inbox Management","n":"Auto-Reply & Qualification Agent","d":"Sales / Operations","t":10,"v":4.58},
  {"i":"Logistics – Brokers","s":"Smart Quoting","n":"Rate Suggestion Agent","d":"Sales / Pricing","t":15,"v":8.13},
  {"i":"Logistics – Brokers","s":"Smart Quoting","n":"Margin Protection Agent","d":"Sales / Pricing","t":15,"v":8.75},
  {"i":"Logistics – Brokers","s":"Smart Quoting","n":"Quote Response Composer Agent","d":"Sales / Operations","t":10,"v":5.00},
  {"i":"Logistics – Brokers","s":"Dynamic Routing","n":"Pickup & Delivery Window Optimizer Agent","d":"Operations / Planning","t":15,"v":8.13},
  {"i":"Logistics – Brokers","s":"Dynamic Routing","n":"Exception Routing Agent","d":"Operations / Planning","t":15,"v":8.75},
  {"i":"Logistics – Brokers","s":"Dynamic Routing","n":"Re-optimization Suggestion Agent","d":"Operations / Planning","t":15,"v":9.38},
  {"i":"Logistics – Brokers","s":"Customer Service","n":"Shipment Status Assistant Agent","d":"Customer Service","t":5,"v":2.29},
  {"i":"Logistics – Brokers","s":"Customer Service","n":"Exception Communication Agent","d":"Customer Service","t":10,"v":4.58},
  {"i":"Logistics – Brokers","s":"Customer Service","n":"Proactive Delay Notification Agent","d":"Customer Service","t":10,"v":4.58},
  {"i":"Logistics – Brokers","s":"Customer Service","n":"Customer SLA Risk Monitor Agent","d":"Customer Service / Operations","t":10,"v":5.00},
  {"i":"Logistics – Brokers","s":"Performance Management","n":"Rep Performance Insights Agent","d":"Sales / Management","t":15,"v":8.13},
  {"i":"Logistics – Brokers","s":"Performance Management","n":"Pipeline Health Agent","d":"Sales / Management","t":15,"v":8.75},
  {"i":"Logistics – Brokers","s":"Performance Management","n":"Coaching Opportunity Agent","d":"Sales / Management","t":15,"v":9.38},
  {"i":"Logistics – Brokers","s":"Onboarding","n":"Customer Requirements Intake Agent","d":"Implementation / Onboarding","t":15,"v":8.13},
  {"i":"Logistics – Brokers","s":"Onboarding","n":"Process Mapping Agent","d":"Implementation / Onboarding","t":15,"v":8.75},
  {"i":"Logistics – Brokers","s":"Onboarding","n":"SOP Drafting Agent","d":"Implementation / Onboarding","t":15,"v":9.38},

  {"i":"Logistics – Forwarders","s":"Freight Quoting","n":"Lane & Mode Recommendation Agent","d":"Sales / Pricing","t":15,"v":8.13},
  {"i":"Logistics – Forwarders","s":"Freight Quoting","n":"Cost Breakdown & Margin Checker Agent","d":"Sales / Pricing","t":15,"v":8.75},
  {"i":"Logistics – Forwarders","s":"Freight Quoting","n":"Multi-Option Quote Builder Agent","d":"Sales / Operations","t":15,"v":9.38},
  {"i":"Logistics – Forwarders","s":"Customs Validation","n":"Document Completeness Agent","d":"Customs / Compliance","t":15,"v":8.13},
  {"i":"Logistics – Forwarders","s":"Customs Validation","n":"Tariff & Classification Checker Agent","d":"Customs / Compliance","t":15,"v":8.75},
  {"i":"Logistics – Forwarders","s":"Customs Validation","n":"Sanctions & Denied Party Check Agent","d":"Customs / Compliance","t":15,"v":9.38},
  {"i":"Logistics – Forwarders","s":"Tracking & Visibility","n":"Exception Detection Agent","d":"Operations / Control Tower","t":10,"v":4.58},
  {"i":"Logistics – Forwarders","s":"Tracking & Visibility","n":"Customer Status Narration Agent","d":"Operations / Control Tower","t":10,"v":4.58},
  {"i":"Logistics – Forwarders","s":"Tracking & Visibility","n":"SLA Risk Monitor Agent","d":"Operations / Control Tower","t":10,"v":5.00},
  {"i":"Logistics – Forwarders","s":"Capacity Management","n":"Capacity Utilization Agent","d":"Operations / Planning","t":15,"v":8.13},
  {"i":"Logistics – Forwarders","s":"Capacity Management","n":"Space Allocation Agent","d":"Operations / Planning","t":15,"v":8.75},
  {"i":"Logistics – Forwarders","s":"Capacity Management","n":"Roll/Short-Ship Risk Agent","d":"Operations / Planning","t":15,"v":9.38},
  {"i":"Logistics – Forwarders","s":"Cost Prediction","n":"Cost Driver Analysis Agent","d":"Finance / FP&A","t":15,"v":8.13},
  {"i":"Logistics – Forwarders","s":"Cost Prediction","n":"Predictive Modeling Agent","d":"Finance / FP&A","t":15,"v":8.75},
  {"i":"Logistics – Forwarders","s":"Cost Prediction","n":"Profitability Insights Agent","d":"Finance / Analytics","t":15,"v":8.75},

  {"i":"Logistics – Shippers","s":"Load Tendering","n":"Carrier Evaluation Agent","d":"Procurement / Logistics","t":15,"v":8.13},
  {"i":"Logistics – Shippers","s":"Load Tendering","n":"Cost Optimization Agent","d":"Procurement / Planning","t":15,"v":8.75},
  {"i":"Logistics – Shippers","s":"Load Tendering","n":"Tender Automation Agent","d":"Procurement / Ops","t":15,"v":8.13},
  {"i":"Logistics – Shippers","s":"Load Tendering","n":"Contract Compliance Agent","d":"Procurement / Audit","t":15,"v":7.50},
  {"i":"Logistics – Shippers","s":"Freight Quoting","n":"Market Rate Agent","d":"Procurement / Pricing","t":15,"v":8.75},
  {"i":"Logistics – Shippers","s":"Freight Quoting","n":"Quote Comparison Agent","d":"Procurement / Analytics","t":15,"v":8.75},
  {"i":"Logistics – Shippers","s":"Freight Quoting","n":"Procurement Strategy Insights Agent","d":"Procurement / Strategy","t":15,"v":8.13},
  {"i":"Logistics – Shippers","s":"Invoice Reconciliation","n":"Invoice Validation Agent","d":"Finance / AP","t":10,"v":4.58},
  {"i":"Logistics – Shippers","s":"Invoice Reconciliation","n":"Discrepancy Detection Agent","d":"Finance / AP","t":10,"v":4.58},
  {"i":"Logistics – Shippers","s":"Invoice Reconciliation","n":"Finance Sync Agent","d":"Finance / AP","t":15,"v":7.50},
  {"i":"Logistics – Shippers","s":"Demand Forecasting","n":"Data Aggregation Agent","d":"Planning / S&OP","t":15,"v":8.75},
  {"i":"Logistics – Shippers","s":"Demand Forecasting","n":"Forecasting Agent","d":"Planning / S&OP","t":15,"v":8.75},
  {"i":"Logistics – Shippers","s":"Demand Forecasting","n":"Capacity Planning Agent","d":"Logistics Planning","t":15,"v":8.13}
];

export const CURRENCIES = {
  EUR: { symbol: '€', code: 'EUR' },
  USD: { symbol: '$', code: 'USD' },
  GBP: { symbol: '£', code: 'GBP' },
  JPY: { symbol: '¥', code: 'JPY' },
};

export const FTE_HOURS = 1800;
